### ISSUE TITLE
Taxonomy for Brewery

### ISSUE THREAD

**Issue by kraftbj** [madasha/beerlog#1]
A brewery taxonomy would be nice to allow easy sorting. If a hierarchical tax is added, could add levels for ownership (e.g. Ab-Inbev->Goose Island), etc.

**Comment by madasha** [comment]
I was thinking about the same thing - this was my original idea for the breweries, however there is this thing: Taxonomies do not get much of a representation in terms of content on their own. So my latest idea is to make breweries a custom post type like beers, but implement relations between beer and a brewery and between brewery and a brewery so that levels of ownership can be implemented as well.

**Comment by madasha** [comment]
This way breweries would be able to have nice "pages" with detailed description, pictures, whatever other meta they would need.

**Comment by kraftbj** [comment]
That makes sense. Core is making progress on giving taxonomies their own meta ( https://core.trac.wordpress.org/ticket/10142 I think is the ticket for that).

Use taxonomies for now with limited content waiting for Core or CPT and engineer a posts-to-posts relationship?

**Comment by madasha** [comment]
Sound like a plan!

I hope to have some time next week to do some pushes to clean some bugs I
know of and to add the breweries taxonomy.

**Comment by madasha** [comment]
There it is... the breweries taxonomy v.0.1 ... I hope to be able to prepare a json with some common ones to come with the plugin

**Comment by kraftbj** [comment]
Awesome; I'll give it a spin this weekend and PR some American breweries.

**Comment by madasha** [comment]
I've forgotten to close this when it was done.
